# core/creator.py
import json
# [Modification 1] Import HumanMessage
from langchain_core.messages import SystemMessage, HumanMessage 
from core.state import AgentState
from core.engine import get_llm
from agents.prompts import SKILL_CREATOR_PROMPT

def creator_node(state: AgentState) -> AgentState:
    """
    Creator node: Generate Python code and Schema based on requirements.
    """
    skill_desc = state["skill_gen_data"]["skill_description"]
    print(f"\n--- [Creator] Generating New Skill for: '{skill_desc}' ---")

    # 1. Prepare Prompt
    prompt = SKILL_CREATOR_PROMPT.format(skill_description=skill_desc)
    
    # 2. Call LLM
    llm = get_llm(temperature=0.2)
    
    # [Modification 2] Key fix: Gemini doesn't like having only a SystemMessage.
    # We wrap the Prompt as a HumanMessage or construct a System + Human combination.
    # The most stable way here is to send it directly as a HumanMessage.
    messages = [HumanMessage(content=prompt)]
    
    try:
        response = llm.invoke(messages)
        
        # [Modification 3] Keep the previous cleaning logic
        content = response.content.replace('```json', '').replace('```', '').strip()
        generated_data = json.loads(content)
        
        # ... (Subsequent code remains unchanged) ...
        # 3. Validate key fields...
        required_keys = ["name", "description", "file_name", "code", "parameters"]
        if not all(key in generated_data for key in required_keys):
            raise ValueError("JSON generated by LLM is missing required fields")

        print(f"--- [Creator] Generated Code for '{generated_data['name']}' ---")

        return {
            "skill_gen_data": {
                "skill_name": generated_data["name"],
                "skill_description": generated_data["description"],
                "file_name": generated_data["file_name"],
                "generated_code": generated_data["code"],
                "parameters": generated_data["parameters"],
                "error_message": None
            }
        }

    except Exception as e:
        print(f"--- [Creator] Error: {str(e)} ---")
        return {
            "skill_gen_data": {
                "error_message": f"Generation failed: {str(e)}"
            }
        }